[project]
authors = ["David Shipman <dshipman@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "renewal-analysis"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
numpy = "<2"
openpyxl = ">=3.1.5,<4"
jupyter = ">=1.1.1,<2"

 [pypi-dependencies]
# ... other PyPI dependencies ...
renewal_analysis = { path = "./renewalwpranalysis", editable = true }
kaleido = ">=1.1.0, <2"
jupyterlab-git = ">=0.51.2, <0.52"
